server:
  port: 8080

management:
  security:
    enabled: false

logging:
  level:
    root: INFO

spring:
  application:
    name: caller-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
      ddl-auto: none
      show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/support_admin_app
    username: postgres
    password: postgres
  cache:
    type: redis
  redis:
    host: ${REDIS_HOST_NAME:localhost}
    port: ${REDIS_PORT:6379}
    lettuce:
      pool:
        max-active: 7
        max-idle: 800
        min-idle: 10
        max-wait: 100000
        shutdown-timeout: 2000ms

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
