server:
  port: 8081

spring:
  application:
    name: encoder-service
  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka

